from enum import Enum


class Errors(str, Enum):
    SUM_IS_BIGGER_THAN_BALANCE = "SUM_IS_BIGGER_THAN_BALANCE"
    THERE_IS_NO_USER = "THERE_IS_NO_USER"
    CONFIRMATION_NEEDED = "CONFIRMATION_NEEDED"
    DUPLICATE_USER = "DUPLICATE_USER"
    EXPIRED_REQUEST = "EXPIRED_REQUEST"
