[project]
name = "zain-hackathon-entry"
version = "0.1.0"
description = "An entry to Zain's hackathon"
readme = "README.md"
authors = [
    { name = "Eyad Jawad", email = "ayadmansr@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "argon2-cffi>=25.1.0",
    "fastapi[standard]>=0.141.1",
    "rapidfuzz>=3.14.6",
    "sqlalchemy>=2.0.54",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "zain_hackathon_entry.main:app"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "ruff>=0.16.8",
]
